version: '3'

services:
  database:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "11111:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'enrollment'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: enrollment_db
